---

- hosts: "{{ hosts | default('jumpbox') }}"
  gather_facts: yes
  tasks:
    - name: test connection
      ping:

    - name: update repository
      apt_repository:
        repo: ppa:vbernat/haproxy-2.2
      become: yes
      become_method: sudo

    - name: update apt cache
      apt: 
        update_cache: yes 
        cache_valid_time: 3600
   
    - name: Install haproxy
      apt:
        name: haproxy=2.2.3-2ppa1~bionic
      become: yes
      become_method: sudo
    
    - name: Enable init script
      replace: dest='/etc/default/haproxy' 
              regexp='ENABLED=0'
              replace='ENABLED=1'
    
    - name: configure systemd to use service and restarted
      systemd:
        daemon_reload: yes
        enabled: yes
        state: restarted
        name: haproxy.service
      become: yes