- hosts: all
  tasks:
   - name: update apt and upgrade all packages
     become: true
     apt:
       upgrade: yes
       update_cache: yes
   - name: ensure nginx is the latest version
     become: true
     apt: name=nginx state=latest
   - name: start nginx
     service:
         name: nginx
         state: started