---

- hosts: "{{ hosts | default('jumpbox') }}"
  vars:
    kafka_exporter_version: 1.2.0
  tasks:
    - name: test connection
      ping:
      
    - name: download Kafka exporter
      get_url:
        url: https://github.com/danielqsj/kafka_exporter/releases/download/v{{ kafka_exporter_version }}/kafka_exporter-{{ kafka_exporter_version }}.linux-amd64.tar.gz
        dest: /tmp
      become: yes

    - name: unarchive Kafka exporter
      unarchive:
        remote_src: yes
        src: /tmp/kafka_exporter-{{ kafka_exporter_version }}.linux-amd64.tar.gz
        dest: /opt/
      become: yes

    - name: Move file Kafka exporter
      command: mv /opt/kafka_exporter-1.2.0.linux-amd64/kafka_exporter /usr/local/bin/
      become: yes

    - name: install unit file to systemd
      template:
        src: kafka_exporter.j2
        dest: /etc/systemd/system/kafka_exporter.service
      become: yes

    - name: configure systemd to use service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: started
        name: kafka_exporter.service
      become: yes