---

- hosts: "{{ hosts | default('jumpbox') }}"
  gather_facts: yes
  tasks:
    - name: test connection
      ping:

    - name: Restart api_gateway
      shell: docker-compose restart api_gateway
      args:
        chdir: /opt/mybb-backend/mybb-app/
      become_user: bbguser
    
    - name: Check container status
      command: ./.api_gw_status.sh
      register: out
      args:
        chdir: /opt/mybb-backend/mybb-app/
      become_user: bbguser
      become: true
      
    - debug: 
        var: out.stdout_lines



