---

- hosts: "{{ hosts | default('jumpbox') }}"
  gather_facts: yes
  tasks:
    - name: test connection
      ping:

    - name: Restart trip_router
      shell: docker-compose restart trip_router
      args:
        chdir: /opt/mybb-backend/mybb-app/
      become_user: bbguser
    
    - name: Check container status
      command: ./.trip_router_status.sh
      register: out
      args:
        chdir: /opt/mybb-backend/mybb-app/
      become_user: bbguser
      become: true
      
    - debug: 
        var: out.stdout_lines
