---

- hosts: "{{ hosts | default('jumpbox') }}"
  gather_facts: yes
  vars:
    RELEASE: 0.17.0
  tasks:
    - name: test connectionnn
      ping:
   
    - name: install unzip
      apt: name=unzip update_cache=yes state=latest
      become: yes

    - name: create group alertmanager
      become: yes
      group:
        name: alertmanager
        state: present

    - name: create user alertmanager
      user:
        name: alertmanager
        group: alertmanager
        createhome: no
        system: yes
        state: present
      become: yes

    - name: create directory data and configuration for alertmanager
      file:
        path: "{{ item }}"
        state: directory
        owner: alertmanager
        group: alertmanager
      become: yes
      with_items:
         - /etc/alertmanager

    - name: Download alert manager
      get_url:
        url: https://github.com/prometheus/alertmanager/releases/download/v{{ RELEASE }}/alertmanager-{{ RELEASE }}.linux-amd64.tar.gz
        dest: /tmp
      become: yes

    - name: unarchive alertmanager
      unarchive:
        remote_src: yes
        src: /tmp/alertmanager-{{ RELEASE }}.linux-amd64.tar.gz
        dest: /tmp/
      become: yes

    - name: Copy file alertmanager to /usr/loca/bin/alertmanager
      copy:
        remote_src: yes
        src: "{{ item }}"
        dest: /usr/local/bin
        owner: alertmanager
        group: alertmanager
      become: yes
      with_items:
         - /tmp/alertmanager-{{ RELEASE }}.linux-amd64/alertmanager
         - /tmp/alertmanager-{{ RELEASE }}.linux-amd64/amtool

    - name: copy file alertmanager yml
      template:
        src: alertmanager.j2
        dest: /etc/alertmanager/alertmanager.yml
        owner: alertmanager
        group: alertmanager
      become: yes
     
    - name: install unit file to systemd
      template:
        src: alert-manager.j2
        dest: /etc/systemd/system/alertmanager.service
      become: yes

    - name: configure systemd to use service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: started
        name: alertmanager.service
      become: yes