---

- hosts: "{{ hosts | default('jumpbox') }}"
  gather_facts: yes
  tasks:
    - name: test connection
      ping:
    
    - name: Restart order_processor
      shell: docker-compose -f docker-compose.production.yaml restart order_processor
      args:
        chdir: /home/bbuser/mybb-app/
      become_user: bbuser
      become: true
    
    - name: Check container status
      command: ./order_processor_status.sh
      register: out
      args:
        chdir: /home/bbuser/
      become_user: bbuser
      become: true
      
    - debug: 
        var: out.stdout_lines


