- hosts: "{{ hosts | default('jumpbox') }}"
  gather_facts: yes
  tasks:
    - name: test connection
      ping:
    
    - name: Install postgresql rpm
      yum:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state: present
      become: true

    - name: Install postgresql-11
      yum:
        name: postgresql11
        state: present
      become: true