---

- hosts: "{{ hosts | default('jumpbox') }}"

  tasks:
    - name: test connectionnn
      ping:

    - name: create group Node exporter
      become: yes
      group:
        name: node_exporter
        state: present

    - name: create user Node exporter
      user:
        name: node_exporter
        group: node_exporter
        createhome: no
        system: yes
        state: present
      become: yes

    - name: create opt directory for Node Exporter
      file:
        path: /opt/node_exporter
        state: directory
      become: yes

    - name: download Node Exporter exporter
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
        dest: /opt/node_exporter
      become: yes

    - name: unarchive Node Exporter exporter
      unarchive:
        remote_src: yes
        src: /opt/node_exporter/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
        dest: /opt/node_exporter
      become: yes

    - name: Move file Node exporter
      command: mv /opt/node_exporter/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter /usr/local/bin/
      become: yes

    - name: install unit file to systemd
      template:
        src: node_exporter.j2
        dest: /etc/systemd/system/node_exporter.service
      become: yes

    - name: configure systemd to use service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: started
        name: node_exporter.service
      become: yes
      become_user: root

    - name: Remove Node Exporter exporter zip
      file:
        path: /opt/node_exporter/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
        state: absent
      become: yes

    - name: Remove Node Exporter exporter folder
      file:
        path: /opt/node_exporter/node_exporter-{{ node_exporter_version }}.linux-amd64
        state: absent
      become: yes