---

- hosts: "{{ hosts | default('jumpbox') }}"
  gather_facts: yes
  tasks:
    - name: test connection
      ping:

    - name: Import InfluxDB GPG signing key
      apt_key: url=https://repos.influxdata.com/influxdb.key state=present
      become: true

    - name: Add InfluxDB repository
      apt_repository: repo='deb https://repos.influxdata.com/ubuntu trusty stable' state=present
      become: true

    - name: Install InfluxDB packages
      apt: name=influxdb state=present
      become: true

    - name: Modify InfluxDB hostname
      replace:
        dest=/etc/influxdb/influxdb.conf
        regexp='hostname = "localhost"'
        replace='hostname = "{{ ansible_hostname }}"'
        backup=yes
    
    - name: configure systemd to use service and restarted
      systemd:
        daemon_reload: yes
        enabled: yes
        state: restarted
        name: influxdb.service
      become: yes

    - name: Create sample database
      command: influx -execute 'CREATE DATABASE prometheus'
      become: yes

    - name: Load some test data into sample database
      uri:
        url: http://localhost:8086/write?db=prometheus
        method: POST
        body: "random_ints,host=server_{{ 10 | random }} value={{ 100 | random }}"
        status_code: 204
      with_sequence: start=1 end=5
    
