---

- hosts: "{{ hosts | default('jumpbox') }}"
  gather_facts: yes
  tasks:
    - name: test connection
      ping:
    
    - name: cleanup container json
      shell: for i in `ls /var/lib/docker/containers/*/*-json.log`; do echo  > $i; done
      ignore_errors: yes
      when: ansible_user == "root"
