---

- hosts: "{{ hosts | default('jumpbox') }}"
  gather_facts: yes
  tasks:
    - name: test connection
      ping:
   
    - name: Download grafana latest
      get_url:
        url: https://dl.grafana.com/oss/release/grafana_7.1.5_amd64.deb
        dest: /tmp/grafana_7.1.5_amd64.deb
      become: yes

    - name: Install deb package grafana
      apt:
        deb: /tmp/grafana_7.1.5_amd64.deb
      become: yes

    - name: configure systemd to use service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: started
        name: grafana-server.service
      become: yes

    - name: "Check if Grafana is accessible."
      uri:
        url: http://0.0.0.0:3000/login
        method: GET
        status_code: 200